PREFIX rfs: <https://framework.regen.network/schema/>
PREFIX rs: <https://schema.regen.network/>

SELECT ?graph ?subject ?predicate ?object ?dataType
WHERE {
    # Query default graph
    {
        ?subject a ?dataType ;
    }
    # Union named graphs
    UNION{
        GRAPH ?graph {
            ?subject a ?dataType ;
        }
   }
}
