id: https://framework.regen.network/schema/Project
name: Project
prefixes:
  linkml: https://w3id.org/linkml/
  rfs: https://framework.regen.network/schema/
  schema: http://schema.org/
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
  dcterms: http://purl.org/dc/terms/
imports:
  - linkml:types
default_curi_maps:
  - semweb_context
default_prefix: rfs
default_range: string

classes:
  Project:
    class_uri: rfs:Project
    slots:
      - name
      - description
      - project_size
      - project_developer
      - id
      - environmentalAuthority
      - marketType
      - bioregion
      - biomeType
      - watershed
      - subWatershed
      - environmentType
      - offchainCreditsInfo
      - projectDuration
      - managementAreas
      - ecologicalConnectivityIndex
      - socialCulturalIndex
      - administrativeArea
      - projectOperator
      - projectMonitor
      - projectOwner
      - projectVerifier
      - projectDeveloper
      - creditClassVersion
      - conservationStatus
    attributes:
      size:
        range: integer
      activity:
      start_date:
      end_date:
      project_type:
      project_verifier:

  ProjectSize:
    class_uri: rfs:ProjectSize
    attributes:
      unit:
        slot_uri: qudt:unit
        required: true
      numericValue:
        range: double
        slot_uri: qudt:numericValue
        required: true

  ProjectRole:
    slots:
      - name
      - description
      - url
    attributes:
      type:
        range: ProjectRoleTypes
        slot_uri: rfs:ProjectRoleType
        required: true
      image:
        slot_uri: schema:image
  
  OffchainCreditsInfo:
    class_uri: rfs:OffchainCreditsInfo
    attributes:
      creditsRegistered:
        range: QuantityValue
        description: The number of credits registered
      creditsAvailable:
        range: QuantityValue
        description: The number of credits available
      creditsRetired:
        range: QuantityValue
        description: The number of credits retired

  Organization:
    class_uri: rfs:Organization
    slots:
      - url
      - showOnProjectPage
      - description
      - image
      - address
    attributes:
      name:
        range: string
        slot_uri: schema:name

  AdministrativeArea:
    class_uri: schema:AdministrativeArea
    slots:
      - name
      - url
  
  QuantityValue:
    class_uri: qudt:QuantityValue
    description: A value that represents a quantity, with a numeric value and a unit.
    attributes:
      numericValue:
        slot_uri: qudt:numericValue
        range: float
        description: The numeric value of the quantity.
      unit:
        slot_uri: qudt:unit
        range: string
        description: The unit of measurement for the quantity.

  ManagementArea:
    class_uri: rfs:ManagementArea
    slots:
      - activity
      - extent


slots:
  name:
    required: true
    description: Name of the project.
    slot_uri: schema:name
  description:
    description: Optional description of the project.
    slot_uri: schema:description
  url:
  project_size:
    range: ProjectSize
    inlined: false
  project_developer:
    range: ProjectRole
    inlined: false
  id:
    range: uriorcurie
    identifier: true
  image:
    slot_uri: schema:image
    description: an image.
  address:
    slot_uri: schema:address
    description: an address.
  showOnProjectPage:
    range: boolean
    description: Whether to show this organization on the project page.
  marketType:
    slot_uri: rfs:marketType
    range: MarketTypeTypes
    description: The type of market for the associated credits.
  bioregion:
    range: string
    slot_uri: rfs:bioregion
    description: The bioregion associated with the project.
    multivalued: true
  biomeType:
    range: string
    slot_uri: rfs:biomeType
    description: The type of biome associated with the project.
    multivalued: true
  watershed:
    range: string
    slot_uri: rfs:watershed
    description: The watershed associated with the project.
  subWatershed:
    range: string
    slot_uri: rfs:subWatershed
    description: The sub-watershed associated with the project.
  environmentType:
    slot_uri: rfs:environmentType
    range: EnvironmentTypeTypes
    description: The type of environment associated with the project.
    multivalued: true
  environmentalAuthority:
    slot_uri: rfs:environmentalAuthority
    range: Organization
    description: The environmental authority associated with the project.
    multivalued: true
    inlined: true
  administrativeArea:
    range: AdministrativeArea
    description: The administrative area associated with the project.
  offchainCreditsInfo:
    slot_uri: rfs:offchainCreditsInfo
    range: OffchainCreditsInfo
    description: Information about offchain credits associated with the project.
  projectDuration:
    slot_uri: rfs:projectDuration
    range: string
    description: The duration of the project.
  ecologicalConnectivityIndex:
    slot_uri: rfs:ecologicalConnectivityIndex
    range: float
    description: The ecological connectivity index of the project.
  socialCulturalIndex:
    slot_uri: rfs:socialCulturalIndex
    range: float
    description: The social cultural index of the project.
  managementAreas:
    slot_uri: rfs:managementAreas
    range: ManagementArea
    description: The management areas associated with the project.
    multivalued: true
    inlined: true
  activity:
    # TODO: associate with regen data standards activities
    slot_uri: rfs:activity
    range: ActivityTypes
    description: the activity.
    multivalued: true
  extent:
    slot_uri: dcterms:extent
    range: QuantityValue
    description: the extent.
  projectOperator:
    slot_uri: rfs:projectOperator
    range: Organization
    description: The organization responsible for operating the project.
  projectMonitor:
    slot_uri: rfs:projectMonitor
    range: Organization
    description: The organization responsible for monitoring the project.
  projectOwner:
    slot_uri: rfs:projectOwner
    range: Organization
    description: The organization responsible for owning the project.
  projectDeveloper:
    slot_uri: rfs:projectDeveloper
    range: Organization
    description: The organization responsible for owning the project.
  projectVerifier:
    slot_uri: rfs:projectVerifier
    range: Organization
    description: The organization responsible for owning the project.
  creditClassVersion:
    slot_uri: rfs:creditClassVersion
    range: string
    description: The version of the credit class used for the project.
  conservationStatus:
    slot_uri: rfs:conservationStatus
    range: ConservationStatusTypes
    description: The conservation status of the project.
  
  

enums:
  ProjectRoleTypes:
    permissible_values:
      individual:
        meaning: rfs:Individual
      organization:
        meaning: rfs:Organization
  MarketTypeTypes:
    description: The type of marketplace
    permissible_values:
      compliance:
        meaning: rfs:ComplianceMarket
        description: a compliance market
      voluntary:
        meaning: rfs:VoluntaryMarket
        description: a voluntary market
  # TODO: these should be imported from a shared vocabulary
  EnvironmentTypeTypes:
    description: The type of ecosystem
    permissible_values:
      # Terrasos values
      cloudForest:
        meaning: rfs:CloudForest
      tropicalSavannah:
        meaning: rfs:TropicalSavannah
      tropicalDryForest:
        meaning: rfs:TropicalDryForest
      tropicalVeryHumidForest:
        meaning: rfs:TropicalVeryHumidForest
      tropicalHumidForest:
        meaning: rfs:TropicalHumidForest
      premontaneHumidForest:
        meaning: rfs:PremontaneHumidForest
      lowMontaneVeryHumidForest:
        meaning: rfs:LowMontaneVeryHumidForest
      riparianForest:
        meaning: rfs:RiparianForest
      # values in the regen data standards md files
      agroforestrySystem:
        meaning: rfs:AgroforestrySystem
      aquacultureSystem:
        meaning: rfs:AquacultureSystem
      cropland:
        meaning: rfs:Cropland
      irrigatedCropland:
        meaning: rfs:IrrigatedCropland
      rainfedCropland:
        meaning: rfs:RainfedCropland
      desert:
        meaning: rfs:Desert
      forest:
        meaning: rfs:Forest
      borealForest:
        meaning: rfs:BorealForest
      temperateForest:
        meaning: rfs:TemperateForest
      tropicalForest:
        meaning: rfs:TropicalForest
      freshwater:
        meaning: rfs:Freshwater
      lake:
        meaning: rfs:Lake
      watercourse:
        meaning: rfs:Watercourse
      grassland:
        meaning: rfs:Grassland
      temperateGrassland:
        meaning: rfs:TemperateGrassland
      tropicalGrassland:
        meaning: rfs:TropicalGrassland
      tundra:
        meaning: rfs:Tundra
      marine:
        meaning: rfs:Marine
      coastal:
        meaning: rfs:Coastal
      coralReef:
        meaning: rfs:CoralReef
      deepWater:
        meaning: rfs:DeepWater
      orchard:
        meaning: rfs:Orchard
      pasture:
        meaning: rfs:Pasture
      permanentIce:
        meaning: rfs:PermanentIce
      savanna:
        meaning: rfs:Savanna
      shrubland:
        meaning: rfs:Shrubland
      borealShrubland:
        meaning: rfs:BorealShrubland
      temperateShrubland:
        meaning: rfs:TemperateShrubland
      tropicalShrubland:
        meaning: rfs:TropicalShrubland
      urbanTrees:
        meaning: rfs:UrbanTrees
      vineyard:
        meaning: rfs:Vineyard
      wetland:
        meaning: rfs:Wetland
      bog:
        meaning: rfs:Bog
      marsh:
        meaning: rfs:Marsh
      swamp:
        meaning: rfs:Swamp
  # TODO: these should be imported from a shared vocabulary
  ConservationStatusTypes:
    description: The conservation status of the project
    permissible_values:
      extinct:
        meaning: rfs:IucnExtinct
        description: Extinct
      extinctInWild:
        meaning: rfs:IucnExtinctInWild
        description: Extinct in the Wild
      criticallyEndangered:
        meaning: rfs:IucnCriticallyEndangered
        description: Critically Endangered
      endangered:
        meaning: rfs:IucnEndangered
        description: Endangered
      vulnerable:
        meaning: rfs:IucnVulnerable
        description: Vulnerable
      nearThreatened:
        meaning: rfs:IucnNearThreatened
        description: Near Threatened
      leastConcern:
        meaning: rfs:IucnLeastConcern
        description: Least Concern
      dataDeficient:
        meaning: rfs:IucnDataDeficient
        description: Data Deficient
      notEvaluated:
        meaning: rfs:IucnNotEvaluated
        description: Not Evaluated
  # TODO: these should be imported from a shared vocabulary
  ActivityTypes:
    description: The type of activity
    permissible_values:
      conservation:
        meaning: rfs:Conservation
        description: a conservation activity
      ecosystemRestoration:
        meaning: rfs:EcosystemRestoration
        description: an ecosystem restoration activity
