id: https://framework.regen.network/schema/
name: Schemas
prefixes:
  linkml: https://w3id.org/linkml/
  rfs: https://framework.regen.network/schema/
  schema: http://schema.org/
  qudt: http://qudt.org/schema/qudt/
  unit: http://qudt.org/vocab/unit/
imports:
  - linkml:types
  - core
  - taxonomy
  - ProjectInfo
  - ProjectPost
  - SDG
  - Impact
  - CreditingProgram
  - CreditProtocol
  - Methodology
  - Registry
  - CreditClassInfo
  - BT01ProjectInfo
  - C01ProjectInfo
  - C02ProjectInfo
default_curi_maps:
  - semweb_context
default_prefix: rfs
default_range: string
