#!/usr/bin/env python3
"""Generate and check the Claim, Attestation and C06 claim JSON-LD examples,
and the playground JSON-LD.

    python3 scripts/claim-examples.py generate    # rewrite examples/*.jsonld
    python3 scripts/claim-examples.py check       # fail if anything is stale or wrong
    python3 scripts/claim-examples.py playground  # write and check data/playground/**/*.jsonld

Run from the schema/ directory. Examples and playground JSON-LD are built
with the published artifacts of the version src/schema.yaml declares
(versions/<version>/, generated by scripts/schema-artifacts.py from
src/schema.yaml and its imports): a document is a YAML fixture plus that
version's JSON-LD context, inline, and an explicit "@type" on the document and
on every nested inlined object, as in the Turtle output.

The check validates every document with both published validators:

- the JSON Schema (json-schema.json) over the authored YAML, with the class as
  entry point (#/$defs/<class>), reporting errors as linkml-validate does;
- the SHACL shapes (shacl.ttl, closed shapes) over the RDF graph of the
  authored JSON-LD, parsed without rdflib's literal normalization so that
  lexical forms, such as the Z suffix of assertedAt, are checked as written.

Each example must be current, its JSON-LD graph isomorphic to the fixture's
Turtle output, and accepted by both validators. The class of a fixture is the
part of its file name before the first "-", as in gen-rdf. Every
examples/*.INVALID-*.yaml document must be rejected by both validators: by JSON
Schema with the error named on its first line ("# expect: ..."), and by SHACL.
Its class is named on a "# class: ..." line, and is Claim when there is none.
A document that breaks a LinkML rule carries a "# shacl: not enforced" line:
the generated SHACL does not express rules, so only JSON Schema must reject it,
and the check reports that SHACL accepts it. An invalid document listed in
INVALID_JSONLD is also published as JSON-LD.

`playground` writes the JSON-LD of every playground fixture next to the
Turtle that gen-rdf writes, and checks that both have the same graph. Numbers
are compared by value: a float written as a YAML integer, such as 500, is
"500"^^xsd:float in JSON-LD and "500.0"^^xsd:float in Turtle.
"""

import glob
import json
import logging
import subprocess
import sys
from pathlib import Path

import jsonschema
import rdflib
import yaml
from jsonschema.exceptions import best_match
from linkml_runtime.utils.schemaview import SchemaView
from pyshacl import validate as shacl_validate
from rdflib.compare import isomorphic
from rdflib.namespace import SH

SCHEMA = "src/schema.yaml"
EXAMPLES = {
    "data/playground/Claim/Claim-generic-001.yaml": "examples/generic-claim.jsonld",
    "data/playground/Claim/Claim-generic-002-revision.yaml": "examples/generic-claim-revision.jsonld",
    "data/playground/C06SiteClaim/C06SiteClaim-mvp-001.yaml": "examples/c06-mvp-claim.jsonld",
    "data/playground/RegistryReviewAttestation/RegistryReviewAttestation-confirmation-001.yaml": "examples/registry-review-attestation.jsonld",
    "data/playground/RegistryFindingAttestation/RegistryFindingAttestation-cl-001.yaml": "examples/registry-finding-attestation.jsonld",
    "data/playground/Attestation/Attestation-generic-001.yaml": "examples/generic-attestation.jsonld",
    "data/playground/C06ProjectClaim/C06ProjectClaim-mvp-001.yaml": "examples/c06-project-claim.jsonld",
    "data/playground/C06CohortClaim/C06CohortClaim-mvp-001.yaml": "examples/c06-cohort-claim.jsonld",
    "data/playground/C06PlotClaim/C06PlotClaim-mvp-001.yaml": "examples/c06-plot-claim.jsonld",
    "data/playground/C06ProjectStatementClaim/C06ProjectStatementClaim-mvp-001.yaml": "examples/c06-project-statement-claim.jsonld",
}
INVALID_GLOB = "examples/*.INVALID-*.yaml"
# Invalid documents also published as JSON-LD, for consumers' tests.
INVALID_JSONLD = {
    "examples/c06-mvp-claim.INVALID-unknown-practice.yaml": "examples/c06-mvp-claim-domain-invalid.jsonld",
}

# Ill-typed literals in the invalid examples are expected; they are reported
# by the validators, not as parser warnings.
logging.getLogger("rdflib.term").setLevel(logging.ERROR)


def run(*args):
    return subprocess.run(args, capture_output=True, text=True)


class Bundle:
    """The published artifacts of the version src/schema.yaml declares."""

    def __init__(self):
        self.view = SchemaView(SCHEMA)
        directory = Path("versions") / self.view.schema.version
        if not directory.exists():
            sys.exit(f"{directory} is missing: run make gen-schema-artifacts")
        self.context = json.loads((directory / "context.jsonld").read_text())["@context"]
        self.json_schema = json.loads((directory / "json-schema.json").read_text())
        self.shapes = rdflib.Graph().parse(directory / "shacl.ttl", format="turtle")


def typed(view, class_name, data):
    """Return data with "@type" on this object and on nested inlined objects."""
    out = {"@type": class_name}
    for key, value in data.items():
        try:
            slot = view.induced_slot(key, class_name)
        except ValueError:
            slot = None  # not in the schema: kept, so validation can reject it
        if slot is not None and slot.range in view.all_classes() and view.is_inlined(slot):
            # Non-objects (such as a bare IRI) are kept as written, so
            # validation can reject them.
            if isinstance(value, list):
                value = [typed(view, slot.range, v) if isinstance(v, dict) else v for v in value]
            elif isinstance(value, dict):
                value = typed(view, slot.range, value)
        out[key] = value
    return out


def build(bundle, class_name, source):
    data = yaml.safe_load(Path(source).read_text())
    document = {"@context": bundle.context, **typed(bundle.view, class_name, data)}
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def authored_graph(jsonld_text):
    """Parse JSON-LD keeping lexical forms as written (no Z -> +00:00)."""
    rdflib.NORMALIZE_LITERALS = False
    try:
        return rdflib.Graph().parse(data=jsonld_text, format="json-ld")
    finally:
        rdflib.NORMALIZE_LITERALS = True


def turtle_graph(fixture, class_name):
    # --no-validate: validation would check LinkML's re-serialized objects,
    # which rewrite Z as +00:00. The authored file is validated by
    # json_schema_check instead.
    result = run(
        "linkml-convert", "-s", SCHEMA, "-C", class_name, "--no-validate",
        "-f", "yaml", "-t", "ttl", fixture,
    )
    if result.returncode != 0:
        sys.exit(f"{fixture}: conversion failed\n{result.stderr}")
    return rdflib.Graph().parse(data=result.stdout, format="turtle")


def json_schema_check(bundle, document, class_name):
    """Validate an authored YAML document with the published JSON Schema."""
    schema = bundle.json_schema
    validator = jsonschema.Draft201909Validator(
        {"$schema": schema["$schema"], "$defs": schema["$defs"], "$ref": f"#/$defs/{class_name}"},
        format_checker=jsonschema.Draft201909Validator.FORMAT_CHECKER,
    )
    data = yaml.safe_load(Path(document).read_text())
    messages = []
    for error in validator.iter_errors(data):
        error = best_match([error])
        messages.append(f"{error.message} in /{'/'.join(str(p) for p in error.absolute_path)}")
    return not messages, "\n".join(messages)


def shacl_report(graph, shapes):
    conforms, results, _ = shacl_validate(graph, shacl_graph=shapes)
    messages = [str(m) for m in results.objects(None, SH.resultMessage)]
    return conforms, messages


def fixture_class(fixture):
    return Path(fixture).name.split("-", 1)[0]


def invalid_class(text):
    for line in text.splitlines():
        if line.startswith("# class:"):
            return line.removeprefix("# class:").strip()
    return "Claim"


def write_or_compare(mode, path, text):
    """Write the file, or report whether it is current. Returns failures."""
    if mode == "generate":
        Path(path).write_text(text)
        return 0
    if not Path(path).exists() or Path(path).read_text() != text:
        print(f"❌ {path} is stale: run make gen-claim-examples")
        return 1
    return 0


def examples(mode):
    bundle = Bundle()
    failures = 0

    for fixture, example in EXAMPLES.items():
        class_name = fixture_class(fixture)
        text = build(bundle, class_name, fixture)
        if write_or_compare(mode, example, text):
            failures += 1
            continue
        valid, output = json_schema_check(bundle, fixture, class_name)
        if valid:
            print(f"✅ {fixture}: conforms to JSON Schema")
        else:
            print(f"❌ {fixture}: JSON Schema violations\n{output}")
            failures += 1
        jsonld = rdflib.Graph().parse(data=text, format="json-ld")
        if isomorphic(jsonld, turtle_graph(fixture, class_name)):
            print(f"✅ {example}: RDF matches {fixture}")
        else:
            print(f"❌ {example}: RDF differs from the Turtle output of {fixture}")
            failures += 1
        conforms, messages = shacl_report(authored_graph(text), bundle.shapes)
        if conforms:
            print(f"✅ {example}: conforms to SHACL")
        else:
            print(f"❌ {example}: SHACL violations {messages}")
            failures += 1

    for invalid in sorted(glob.glob(INVALID_GLOB)):
        content = Path(invalid).read_text()
        expected = content.splitlines()[0].removeprefix("# expect:").strip()
        class_name = invalid_class(content)
        valid, output = json_schema_check(bundle, invalid, class_name)
        if not valid and expected in output:
            print(f"✅ {invalid}: JSON Schema rejects it ({expected})")
        else:
            print(f"❌ {invalid}: expected JSON Schema rejection with '{expected}'\n{output}")
            failures += 1
        text = build(bundle, class_name, invalid)
        if invalid in INVALID_JSONLD:
            failures += write_or_compare(mode, INVALID_JSONLD[invalid], text)
        conforms, messages = shacl_report(authored_graph(text), bundle.shapes)
        if "# shacl: not enforced" in content:
            if conforms:
                print(f"ℹ️  {invalid}: SHACL accepts it (a LinkML rule; not expressed in SHACL)")
            else:
                print(f"❌ {invalid}: marked 'shacl: not enforced' but SHACL rejects it ({messages[0][:80]})")
                failures += 1
        elif not conforms:
            print(f"✅ {invalid}: SHACL rejects it ({messages[0][:80]})")
        else:
            print(f"❌ {invalid}: SHACL accepts it")
            failures += 1

    missing = set(INVALID_JSONLD) - set(glob.glob(INVALID_GLOB))
    for invalid in sorted(missing):
        print(f"❌ {invalid}: listed in INVALID_JSONLD but missing")
        failures += 1

    if failures:
        sys.exit(f"{failures} example check(s) failed")


def by_value(graph):
    """The graph with numeric literals in canonical form, to compare by value."""
    out = rdflib.Graph()
    for s, p, o in graph:
        if isinstance(o, rdflib.Literal) and isinstance(o.value, (int, float)) and not isinstance(o.value, bool):
            o = rdflib.Literal(float(o.value), datatype=o.datatype)
        out.add((s, p, o))
    return out


def playground():
    bundle = Bundle()
    failures = 0
    fixtures = sorted(glob.glob("data/playground/*/*.yaml"))
    for fixture in fixtures:
        path = Path(fixture)
        text = build(bundle, fixture_class(fixture), fixture)
        path.with_suffix(".jsonld").write_text(text)
        turtle = path.with_suffix(".ttl")
        if not turtle.exists():
            print(f"❌ {turtle} is missing: run make gen-rdf")
            failures += 1
            continue
        jsonld = rdflib.Graph().parse(data=text, format="json-ld")
        if isomorphic(by_value(jsonld), by_value(rdflib.Graph().parse(turtle, format="turtle"))):
            print(f"✅ {path.with_suffix('.jsonld')}: RDF matches {turtle}")
        else:
            print(f"❌ {path.with_suffix('.jsonld')}: RDF differs from {turtle}")
            failures += 1
    print(f"Playground JSON-LD: {len(fixtures) - failures} of {len(fixtures)} match their Turtle")
    if failures:
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in ("generate", "check", "playground"):
        sys.exit(__doc__)
    if sys.argv[1] == "playground":
        playground()
    else:
        examples(sys.argv[1])
